dist: xenial
language: node_js
node_js:
      - 10

cache:
  directories:
    - node_modules

branches:
  except:
  - "/^renovate\\/.+$/"

# We need to use yarn to use lerna #yakshaving
install:
  - yarn global add lerna
  - yarn
script:
  yarn test

