name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ <%= nodeVersions.join(", ") -%> ]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
<% if (type === 'mono')  { -%>
      - run: yarn global add lerna
<% } %>
      - run: yarn
      - run: yarn test
