language: node_js
sudo: false
node_js:
  <% nodeVersions.forEach(function(version){ -%>
    - <%= version %>
  <% }); %>
cache:
  directories:
    - node_modules

<% if (type === 'mono')  { -%>
# We need to use yarn to use lerna #yakshaving
install:
  yarn global add lerna
script:
  yarn test
<% } %>
