dist: xenial
language: node_js
node_js:
  <% nodeVersions.forEach(function(version){ -%>
    - <%= version %>
  <% }); %>
cache: yarn

# Don't run builds for renovate PRs
if: NOT head_branch =~ ^renovate

<% if (type === 'mono')  { -%>
# We need to use yarn to use lerna #yakshaving
install:
  - yarn global add lerna
  - yarn
script:
  yarn test
<% } %>
